/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSpeedRouteImport } from './routes/app.speed'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRhythmsRouteImport } from './routes/app.rhythms'
import { Route as AppPracticeRouteImport } from './routes/app.practice'
import { Route as AppPadRouteImport } from './routes/app.pad'
import { Route as AppNotationRouteImport } from './routes/app.notation'
import { Route as AppMetronomeRouteImport } from './routes/app.metronome'
import { Route as AppCoordinationRouteImport } from './routes/app.coordination'
import { Route as AppRudimentsIndexRouteImport } from './routes/app.rudiments.index'
import { Route as AppRudimentsIdRouteImport } from './routes/app.rudiments.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSpeedRoute = AppSpeedRouteImport.update({
  id: '/speed',
  path: '/speed',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRhythmsRoute = AppRhythmsRouteImport.update({
  id: '/rhythms',
  path: '/rhythms',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRoute,
} as any)
const AppPadRoute = AppPadRouteImport.update({
  id: '/pad',
  path: '/pad',
  getParentRoute: () => AppRoute,
} as any)
const AppNotationRoute = AppNotationRouteImport.update({
  id: '/notation',
  path: '/notation',
  getParentRoute: () => AppRoute,
} as any)
const AppMetronomeRoute = AppMetronomeRouteImport.update({
  id: '/metronome',
  path: '/metronome',
  getParentRoute: () => AppRoute,
} as any)
const AppCoordinationRoute = AppCoordinationRouteImport.update({
  id: '/coordination',
  path: '/coordination',
  getParentRoute: () => AppRoute,
} as any)
const AppRudimentsIndexRoute = AppRudimentsIndexRouteImport.update({
  id: '/rudiments/',
  path: '/rudiments/',
  getParentRoute: () => AppRoute,
} as any)
const AppRudimentsIdRoute = AppRudimentsIdRouteImport.update({
  id: '/rudiments/$id',
  path: '/rudiments/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/coordination': typeof AppCoordinationRoute
  '/app/metronome': typeof AppMetronomeRoute
  '/app/notation': typeof AppNotationRoute
  '/app/pad': typeof AppPadRoute
  '/app/practice': typeof AppPracticeRoute
  '/app/rhythms': typeof AppRhythmsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/speed': typeof AppSpeedRoute
  '/app/': typeof AppIndexRoute
  '/app/rudiments/$id': typeof AppRudimentsIdRoute
  '/app/rudiments/': typeof AppRudimentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/coordination': typeof AppCoordinationRoute
  '/app/metronome': typeof AppMetronomeRoute
  '/app/notation': typeof AppNotationRoute
  '/app/pad': typeof AppPadRoute
  '/app/practice': typeof AppPracticeRoute
  '/app/rhythms': typeof AppRhythmsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/speed': typeof AppSpeedRoute
  '/app': typeof AppIndexRoute
  '/app/rudiments/$id': typeof AppRudimentsIdRoute
  '/app/rudiments': typeof AppRudimentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/coordination': typeof AppCoordinationRoute
  '/app/metronome': typeof AppMetronomeRoute
  '/app/notation': typeof AppNotationRoute
  '/app/pad': typeof AppPadRoute
  '/app/practice': typeof AppPracticeRoute
  '/app/rhythms': typeof AppRhythmsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/speed': typeof AppSpeedRoute
  '/app/': typeof AppIndexRoute
  '/app/rudiments/$id': typeof AppRudimentsIdRoute
  '/app/rudiments/': typeof AppRudimentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/app/coordination'
    | '/app/metronome'
    | '/app/notation'
    | '/app/pad'
    | '/app/practice'
    | '/app/rhythms'
    | '/app/settings'
    | '/app/speed'
    | '/app/'
    | '/app/rudiments/$id'
    | '/app/rudiments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/app/coordination'
    | '/app/metronome'
    | '/app/notation'
    | '/app/pad'
    | '/app/practice'
    | '/app/rhythms'
    | '/app/settings'
    | '/app/speed'
    | '/app'
    | '/app/rudiments/$id'
    | '/app/rudiments'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/app/coordination'
    | '/app/metronome'
    | '/app/notation'
    | '/app/pad'
    | '/app/practice'
    | '/app/rhythms'
    | '/app/settings'
    | '/app/speed'
    | '/app/'
    | '/app/rudiments/$id'
    | '/app/rudiments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/speed': {
      id: '/app/speed'
      path: '/speed'
      fullPath: '/app/speed'
      preLoaderRoute: typeof AppSpeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rhythms': {
      id: '/app/rhythms'
      path: '/rhythms'
      fullPath: '/app/rhythms'
      preLoaderRoute: typeof AppRhythmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/practice': {
      id: '/app/practice'
      path: '/practice'
      fullPath: '/app/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pad': {
      id: '/app/pad'
      path: '/pad'
      fullPath: '/app/pad'
      preLoaderRoute: typeof AppPadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notation': {
      id: '/app/notation'
      path: '/notation'
      fullPath: '/app/notation'
      preLoaderRoute: typeof AppNotationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/metronome': {
      id: '/app/metronome'
      path: '/metronome'
      fullPath: '/app/metronome'
      preLoaderRoute: typeof AppMetronomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coordination': {
      id: '/app/coordination'
      path: '/coordination'
      fullPath: '/app/coordination'
      preLoaderRoute: typeof AppCoordinationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rudiments/': {
      id: '/app/rudiments/'
      path: '/rudiments'
      fullPath: '/app/rudiments/'
      preLoaderRoute: typeof AppRudimentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rudiments/$id': {
      id: '/app/rudiments/$id'
      path: '/rudiments/$id'
      fullPath: '/app/rudiments/$id'
      preLoaderRoute: typeof AppRudimentsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCoordinationRoute: typeof AppCoordinationRoute
  AppMetronomeRoute: typeof AppMetronomeRoute
  AppNotationRoute: typeof AppNotationRoute
  AppPadRoute: typeof AppPadRoute
  AppPracticeRoute: typeof AppPracticeRoute
  AppRhythmsRoute: typeof AppRhythmsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSpeedRoute: typeof AppSpeedRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRudimentsIdRoute: typeof AppRudimentsIdRoute
  AppRudimentsIndexRoute: typeof AppRudimentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoordinationRoute: AppCoordinationRoute,
  AppMetronomeRoute: AppMetronomeRoute,
  AppNotationRoute: AppNotationRoute,
  AppPadRoute: AppPadRoute,
  AppPracticeRoute: AppPracticeRoute,
  AppRhythmsRoute: AppRhythmsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSpeedRoute: AppSpeedRoute,
  AppIndexRoute: AppIndexRoute,
  AppRudimentsIdRoute: AppRudimentsIdRoute,
  AppRudimentsIndexRoute: AppRudimentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
